name: ADF_Deployment(Full)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        type: choice
        options:
          - 'dev'
          - 'stage'
          - 'prod'
        required: true
      Triggers-status:
        description: 'Provide the status of the triggers to be deployed'
        type: choice
        options:
          - 'Started'
          - 'Stopped'
        default: 'Started'
    
permissions:
  contents: read
  id-token: write

jobs:
  Selective_ADF_Deployment: 
    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/Main_ADF_full_deployment.yml@develop
    with:
      environment: ${{ inputs.environment }}
      Triggers-status: ${{ inputs.Triggers-status }}
    secrets: inherit
