name: ADF_Deployment(Full)

on:
  push:
    branches:
      - develop
      - stage
      
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        type: choice
        options:
          - 'dev'
          - 'stage'
          - 'prod'
        required: true
      Triggers-status:
        description: 'Provide the status of the triggers to be deployed'
        type: choice
        options:
          - 'Started'
          - 'Stopped'
        default: 'Started'
    
permissions:
  contents: read
  id-token: write

jobs:
  Deploying_To_Dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    uses: Aman-PN/Github_Workflows/.github/workflows/Main_ADF_full_deployment.yml@main
    with:
      environment: dev
    secrets: inherit
    
  Deploying_To_Stage:
    if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
    uses: Aman-PN/Github_Workflows/.github/workflows/Main_ADF_full_deployment.yml@main
    with:
      environment: stage
    secrets: inherit

  Selective_ADF_Deployment:
    if: github.event_name == 'workflow_dispatch'
    uses: Aman-PN/Github_Workflows/.github/workflows/Main_ADF_full_deployment.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit    
    # with:
    #   environment: ${{ inputs.environment }}
    #   Triggers-status: ${{ inputs.Triggers-status }}
    # secrets: inherit 