name: ADF_Deployment(Selective)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        type: choice
        options:
          - 'dev'
          - 'stage'
          - 'prod'
        required: true
      Pipelines:
        description: 'Enter the pipeline name'
        type: string
      LinkedServices:
        description: 'Enter the linked service name'
        type: string
      Datasets:
        description: 'Enter the dataset name'
        type: string
      Triggers:
        description: 'Enter the trigger name'
        type: string
      Triggers-status:
        description: 'Provide the status of the triggers to be deployed'
        type: choice
        options:
          - 'Started'
          - 'Stopped'
        default: 'Started'
    
permissions:
  contents: read
  id-token: write

jobs:
  Selective_ADF_Deployment: 
    uses: Aman-PN/Github_Workflows/.github/workflows/Main_ADF_selective_deployment.yml@main
    with:
      environment: ${{ inputs.environment }}
      Pipelines: ${{ inputs.Pipelines }}
      LinkedServices: ${{ inputs.LinkedServices }}
      Datasets: ${{ inputs.Datasets }}
      Triggers: ${{ inputs.Triggers }}
      Triggers-status: ${{ inputs.Triggers-status }}
    secrets: inherit