name: Databricks_Deployment_Workflow

on:
  push:
    branches:
      - develop
      - stage

    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - '**/*.txt'

  workflow_dispatch:
    inputs:
      environment:
        description: 'deploy to'
        type: environment
        required: true
        default: 'dev'
      databricks_code_deploy:
          description: 'deploy code to databricks workspace'
          required: false
          type: boolean
          default: false
      databricks_notebook_deploy:
          description: 'deploy specific notebooks to databricks workspace. If databricks_code_deploy is selected then this should not be selected.'
          required: false
          type: boolean
          default: false
      source_folder:
          description: 'Enter the source folder path(Local path) & use / for sub_path'
          required: false
          type: string
          default: '.'
      destionation_folder:
          description: 'Enter the destination folder path(/Remote path) & use / at starting and for sub_path'
          required: false
          type: string
          default: '/batch'

permissions:
  contents: read
  id-token: write

jobs:
  dev_code_deploy_to_databricks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop
    with:
      environment: dev
      source_folder: .
      destionation_folder: '/batch'
      backup_workspace: false
      install_libraries: false
      source_target_sync: true
      databricks_code_deploy: true
    secrets: inherit
    
  stage_code_deploy_to_databricks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/stage'

    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop
    with:
      environment: stage
      source_folder: .
      destionation_folder: '/batch'
      install_libraries: false
      backup_workspace: false
      source_target_sync: true
      databricks_code_deploy: true
    secrets: inherit
    
  code_deploy_to_databricks:
    if: github.event_name == 'workflow_dispatch' && ( github.event.inputs.databricks_code_deploy == 'true' || github.event.inputs.databricks_notebook_deploy == 'true' )

    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop

    with:
      environment: ${{ inputs.environment }}
      source_folder: ${{ inputs.source_folder }}
      destionation_folder: ${{ inputs.destionation_folder }}
      databricks_code_deploy: ${{ inputs.databricks_code_deploy }}
      databricks_notebook_deploy: ${{ inputs.databricks_notebook_deploy }}
      backup_workspace: false

    secrets: inherit
