name: Databricks_Deployment_Workflow

on:
  push:
    branches:
      - develop
      - stage
    paths:
      - "ADB-PoC/**"

    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - '**/*.txt'

  workflow_dispatch:
    paths:
      - "ADB-PoC/**"
    inputs:
      environment:
        description: 'deploy to'
        type: environment
        required: true
        default: 'dev'
      # destionation_folder:
      #     description: 'Enter the destination folder path(/Remote path) & use / at starting and for sub_path'
      #     required: false
      #     type: string
      #     default: '/batch'

permissions:
  contents: read
  id-token: write

jobs:
  dev_code_deploy_to_databricks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop
    with:
      environment: dev
      #destionation_folder: '/batch'
    secrets: inherit
    
  stage_code_deploy_to_databricks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/stage'

    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop
    with:
      environment: stage
      #destionation_folder: '/batch'
    secrets: inherit
    
  code_deploy_to_databricks:
    if: github.event_name == 'workflow_dispatch'
    uses: Aman-PN/ADF_Deployment-PoC/.github/workflows/main_databricks_workflow.yml@develop
    with:
      environment: ${{ inputs.environment }}
      #destionation_folder: '/batch'
    secrets: inherit
